In [88]:
print("hi")

hi

In [89]:
from pathlib import Path
base_path = Path().resolve().parent
print(base_path)
file_path=base_path/"twcs"/"twcs.csv"

D:\Projects\ResolveAI

In [90]:
import pandas as pd
import numpy as np

In [91]:
df=pd.read_csv(file_path)

In [92]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [93]:
df['author_id'].value_counts()

author_id
AmazonHelp      169840
AppleSupport    106860
Uber_Support     56270
SpotifyCares     43265
Delta            42253
                 ...
823866               1
823867               1
823868               1
823869               1
823870               1
Name: count, Length: 702777, dtype: int64

In [94]:
df.dtypes

tweet_id                     int64
author_id                      str
inbound                       bool
created_at                     str
text                           str
response_tweet_id              str
in_response_to_tweet_id    float64
dtype: object

In [95]:
unique_author_ids = df["author_id"].unique()

print(unique_author_ids)

<StringArray>
[    'sprintcare',         '115712',         '115713',         '115715',
   'Ask_Spectrum',         '115716',         '115717',         '115718',
 'VerizonSupport',         '115719',
 ...
         '823861',         '823862',         '823863',         '823864',
         '823865',         '823866',         '823867',         '823868',
         '823869',         '823870']
Length: 702777, dtype: str

In [96]:
spotify_tweets = df[df["author_id"] == "SpotifyCares"].copy()

In [97]:
print(spotify_tweets.shape)

(43265, 7)

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                str
 2   inbound                  bool
 3   created_at               str
 4   text                     str
 5   response_tweet_id        str
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 131.4 MB

In [99]:
df.describe()

           tweet_id  in_response_to_tweet_id
count  2.811774e+06             2.017439e+06
mean   1.504565e+06             1.463141e+06
std    8.616450e+05             8.665730e+05
min    1.000000e+00             1.000000e+00
25%    7.601652e+05             7.155105e+05
50%    1.507772e+06             1.439805e+06
75%    2.253296e+06             2.220646e+06
max    2.987950e+06             2.987950e+06

In [100]:
df.head(3)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0

In [101]:
df.isnull().sum()

tweet_id                         0
author_id                        0
inbound                          0
created_at                       0
text                             0
response_tweet_id          1040629
in_response_to_tweet_id     794335
dtype: int64

In [102]:
for _, row in spotify_tweets.head(3).iterrows():
    print("=" * 100)
    print(f"Tweet ID: {row['tweet_id']}")
    print(f"Author: {row['author_id']}")
    print(f"Inbound: {row['inbound']}")
    print(f"Created: {row['created_at']}")
    print(f"Response Tweet ID: {row['response_tweet_id']}")
    print(f"In Response To: {row['in_response_to_tweet_id']}")
    print(f"Text: {row['text']}")

====================================================================================================
Tweet ID: 848
Author: SpotifyCares
Inbound: False
Created: Tue Oct 31 22:28:16 +0000 2017
Response Tweet ID: 849
In Response To: 850.0
Text: @115887 Hmm. Can you try restarting your device by holding the Sleep/Wake + Volume Down buttons for 10 seconds? Keep us posted /LS
====================================================================================================
Tweet ID: 851
Author: SpotifyCares
Inbound: False
Created: Tue Oct 31 23:39:03 +0000 2017
Response Tweet ID: nan
In Response To: 849.0
Text: @115887 Could you send us a DM with your account's email address? We'll take a look backstage /CH https://t.co/ldFdZRiNAt
====================================================================================================
Tweet ID: 852
Author: SpotifyCares
Inbound: False
Created: Tue Oct 31 21:04:13 +0000 2017
Response Tweet ID: 850
In Response To: 853.0
Text: @115887 Thanks. Just to be sure, are you Free or Premium? Also, can you give us more info on what happens when you try using it? /CB

In [103]:
# Check for null values
null_count = df["tweet_id"].isna().sum()

# Check for duplicates
duplicate_count = df["tweet_id"].duplicated().sum()

# Check uniqueness
is_unique = df["tweet_id"].is_unique

print("Total rows:", len(df))
print("Null tweet_ids:", null_count)
print("Duplicate tweet_ids:", duplicate_count)
print("Is tweet_id unique?:", is_unique)

Total rows: 2811774
Null tweet_ids: 0
Duplicate tweet_ids: 0
Is tweet_id unique?: True

In [104]:

for _, row in df[df['tweet_id']==849].iterrows():
    print("=" * 100)
    print(f"Tweet ID: {row['tweet_id']}")
    print(f"Author: {row['author_id']}")
    print(f"Inbound: {row['inbound']}")
    print(f"Created: {row['created_at']}")
    print(f"Response Tweet ID: {row['response_tweet_id']}")
    print(f"In Response To: {row['in_response_to_tweet_id']}")
    print(f"Text: {row['text']}")

====================================================================================================
Tweet ID: 849
Author: 115887
Inbound: True
Created: Tue Oct 31 23:36:20 +0000 2017
Response Tweet ID: 851
In Response To: 848.0
Text: @SpotifyCares doesn’t work and i even tried deleting the app

In [105]:
df["author_id"] = df["author_id"].str.strip()

In [106]:
df["created_at"] = pd.to_datetime(
    df["created_at"],
    format="%a %b %d %H:%M:%S %z %Y",
    errors="coerce"
)

In [107]:
print(df["created_at"].head())
print(df["created_at"].dtype)
print("Invalid dates:", df["created_at"].isna().sum())

0   2017-10-31 22:10:47+00:00
1   2017-10-31 22:11:45+00:00
2   2017-10-31 22:08:27+00:00
3   2017-10-31 21:54:49+00:00
4   2017-10-31 21:49:35+00:00
Name: created_at, dtype: datetime64[us, UTC]
datetime64[us, UTC]
Invalid dates: 0

In [108]:
df["in_response_to_tweet_id"] = (
    df["in_response_to_tweet_id"]
    .astype("Int64")
)

In [109]:
print(df["response_tweet_id"].head(20).to_list())

['2', nan, '1', '3', '4', '5,7', '9,6,10', nan, '11,13,14', '12', '15', '16', '17', nan, '19', '22,23', '25', '26', '27', nan]

In [110]:
multi_response = df["response_tweet_id"].dropna().str.contains(",")

print("Multiple response IDs:", multi_response.sum())

Multiple response IDs: 222426

In [111]:
def parse_response_ids(value):
    if pd.isna(value):
        return []
    
    return [
        int(x.strip())
        for x in str(value).split(",")
        if x.strip().isdigit()
    ]

df["response_ids"] = df["response_tweet_id"].apply(parse_response_ids)

In [112]:
print(df["response_ids"].head(20).to_list())

[[2], [], [1], [3], [4], [5, 7], [9, 6, 10], [], [11, 13, 14], [12], [15], [16], [17], [], [19], [22, 23], [25], [26], [27], []]

In [113]:
tweet_ids = set(df["tweet_id"])

In [114]:
parent_ids = df["in_response_to_tweet_id"].dropna()

missing_parents = parent_ids[
    ~parent_ids.isin(tweet_ids)
]

print("Missing parent tweets:", len(missing_parents))

Missing parent tweets: 3862

In [115]:
def find_missing_responses(response_ids):
    return [
        x for x in response_ids
        if x not in tweet_ids
    ]

df["missing_response_ids"] = df["response_ids"].apply(
    find_missing_responses
)

print(
    "Rows with missing response tweets:",
    (df["missing_response_ids"].str.len() > 0).sum()
)

Rows with missing response tweets: 58837

In [116]:
total_rows = len(df)

print(
    f"Missing parent percentage: "
    f"{3862 / total_rows * 100:.3f}%"
)

print(
    f"Rows with missing responses percentage: "
    f"{58837 / total_rows * 100:.3f}%"
)

Missing parent percentage: 0.137%
Rows with missing responses percentage: 2.093%

In [117]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
0,1,sprintcare,False,2017-10-31 22:10:47+00:00,@115712 I understand. I would like to assist y...,2,3,[2],[]
1,2,115712,True,2017-10-31 22:11:45+00:00,@sprintcare and how do you propose we do that,NaN,1,[],[]
2,3,115712,True,2017-10-31 22:08:27+00:00,@sprintcare I have sent several private messag...,1,4,[1],[]
3,4,sprintcare,False,2017-10-31 21:54:49+00:00,@115712 Please send us a Private Message so th...,3,5,[3],[]
4,5,115712,True,2017-10-31 21:49:35+00:00,@sprintcare I did.,4,6,[4],[]

In [118]:
missing_parent_records = df[
    df["in_response_to_tweet_id"].isin(missing_parents)
]

display(missing_parent_records)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
138,222,115760,True,2017-10-31 19:05:30+00:00,@108162 @115761 @ATVIAssist tried that there w...,221,223,[221],[]
1035,1621,AzureSupport,False,2017-10-31 22:11:47+00:00,@116051 Sorry to hear your having trouble. Cou...,1620,1622,[1620],[]
2817,3745,AmazonHelp,False,2017-10-31 22:36:29+00:00,"@116616 David, te recomendamos no compartir in...",3744,3746,[3744],[]
2848,3777,116625,True,2017-10-31 22:53:05+00:00,@AppleSupport I've also forced the app to clos...,3775,3779,[3775],[]
4082,5530,Ask_Spectrum,False,2017-10-31 23:08:39+00:00,@117003 Please remove that from public. I have...,5529,5531,[5529],[]
...,...,...,...,...,...,...,...,...,...
2806774,2983022,822583,True,2017-09-05 16:53:03+00:00,@158 @822582 @822574 @822577 @822575 @822591 @...,2983021,2983023,[2983021],[]
2808821,2985054,817721,True,2017-11-30 06:15:38+00:00,@Safaricom_Care No..there is an option to chan...,2985053,2985055,[2985053],[]
2808942,2985175,823145,True,2017-11-29 21:37:14+00:00,@115236 @115237 That is not argos,2985174,2985176,[2985174],[]
2810120,2986334,823444,True,2017-10-31 21:42:58+00:00,@115233 @115858 @AppleSupport I’ve been seeing...,2986332,2986335,[2986332],[]
2811361,2987548,124636,True,2017-10-31 21:25:52+00:00,@43755 Exactly and now I'm in one that has dir...,2987546,2987549,[2987546],[]

In [119]:
df[df['author_id']==223]

Empty DataFrame
Columns: [tweet_id, author_id, inbound, created_at, text, response_tweet_id, in_response_to_tweet_id, response_ids, missing_response_ids]
Index: []

In [120]:
spotify_tweets = df[df["author_id"] == "SpotifyCares"].copy()

In [121]:
print(spotify_tweets.shape)

(43265, 9)

In [122]:
spotify_tweets.isnull().sum()

tweet_id                       0
author_id                      0
inbound                        0
created_at                     0
text                           0
response_tweet_id          29479
in_response_to_tweet_id       22
response_ids                   0
missing_response_ids           0
dtype: int64

In [123]:
spotify_tweets.info()

<class 'pandas.DataFrame'>
Index: 43265 entries, 540 to 2811503
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 43265 non-null  int64
 1   author_id                43265 non-null  str
 2   inbound                  43265 non-null  bool
 3   created_at               43265 non-null  datetime64[us, UTC]
 4   text                     43265 non-null  str
 5   response_tweet_id        13786 non-null  str
 6   in_response_to_tweet_id  43243 non-null  Int64
 7   response_ids             43265 non-null  object
 8   missing_response_ids     43265 non-null  object
dtypes: Int64(1), bool(1), datetime64[us, UTC](1), int64(1), object(2), str(3)
memory usage: 3.1+ MB

In [124]:
spotify_tweet_ids = set(spotify_tweets["tweet_id"])

In [125]:
print("Spotify rows:", len(spotify_tweets))

print(
    "NULL response_tweet_id:",
    spotify_tweets["response_tweet_id"].isna().sum()
)

print(
    "NULL in_response_to_tweet_id:",
    spotify_tweets["in_response_to_tweet_id"].isnull().sum()
)

Spotify rows: 43265
NULL response_tweet_id: 29479
NULL in_response_to_tweet_id: 22

In [126]:
spotify_tweets = spotify_tweets.sort_values(
    by="created_at",
    ascending=True
).reset_index(drop=True)

In [127]:
spotify_tweets[
        spotify_tweets["in_response_to_tweet_id"].isna()
    ]

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
21,66018,SpotifyCares,False,2017-02-10 15:00:04+00:00,Let the pre-spring clean commence! https://t.c...,66017,<NA>,[66017],[]
481,293875,SpotifyCares,False,2017-10-04 14:20:13+00:00,Do not disturb 🚪 https://t.co/RZqTYGHtGB,"293876,293877,293878,293879,293874,293880,2938...",<NA>,"[293876, 293877, 293878, 293879, 293874, 29388...","[293883, 293885, 293888]"
4188,411607,SpotifyCares,False,2017-10-10 00:08:19+00:00,"Hey, help's here! Can you tell us what device ...","411608,411609,411610,411611,411612,411613,4116...",<NA>,"[411608, 411609, 411610, 411611, 411612, 41161...","[411608, 411609, 411610, 411612, 411613, 41161..."
5208,753638,SpotifyCares,False,2017-10-11 14:04:56+00:00,Attention playlist curators! We have two @1613...,"753637,753639,753640,753641,753642,753643,7536...",<NA>,"[753637, 753639, 753640, 753641, 753642, 75364...","[753641, 753643, 753646, 753649, 753651, 753652]"
8584,1261925,SpotifyCares,False,2017-10-16 04:32:42+00:00,Hi Will! Help's here. Can you let us know your...,"1261926,1261927,1261924,1261928,1261929,126193...",<NA>,"[1261926, 1261927, 1261924, 1261928, 1261929, ...","[1261927, 1261929, 1261931, 1261932]"
14226,1056940,SpotifyCares,False,2017-10-23 11:29:45+00:00,Discover Weekly: hand-picked just for you (but...,"1056939,1056941,1056942,1056943",<NA>,"[1056939, 1056941, 1056942, 1056943]",[]
19658,12091,SpotifyCares,False,2017-10-31 15:00:14+00:00,Resurrect your playlists 👻 https://t.co/8y3l3q...,"12090,12092,12093,12094,12095,12096,12097,1209...",<NA>,"[12090, 12092, 12093, 12094, 12095, 12096, 120...",[12102]
20484,58281,SpotifyCares,False,2017-11-01 20:15:35+00:00,@129236 Hey there! Can you send us the Album L...,58280,<NA>,[58280],[]
22085,1537070,SpotifyCares,False,2017-11-03 23:25:46+00:00,@476554 Got it. Find out how to reset your pas...,"1537071,1537069",<NA>,"[1537071, 1537069]",[1537071]
25116,2175496,SpotifyCares,False,2017-11-08 14:30:00+00:00,@637790 ¡Hola! La devolución del dinero depend...,"2175497,2175495",<NA>,"[2175497, 2175495]",[2175497]
25958,79405,SpotifyCares,False,2017-11-09 14:25:07+00:00,Twice the room to talk about that new tune! Sh...,"79404,79406,79407,79408,79409,79410,79411,7941...",<NA>,"[79404, 79406, 79407, 79408, 79409, 79410, 794...","[79406, 79414, 79416, 79421, 79423]"
27501,2276876,SpotifyCares,False,2017-11-11 14:33:13+00:00,"@662172 Hey, sorry for the wait! We've just re...",2276875,<NA>,[2276875],[]
31523,2582043,SpotifyCares,False,2017-11-16 22:42:34+00:00,@154077 Hey Patricia! We've just sent a DM you...,"2582042,2582044",<NA>,"[2582042, 2582044]",[2582044]
34340,2801580,SpotifyCares,False,2017-11-21 21:19:57+00:00,@663174 Hey there! We've just sent you a DM 🙂 /VK,"2801581,2801579",<NA>,"[2801581, 2801579]",[2801581]
35429,678427,SpotifyCares,False,2017-11-23 05:50:52+00:00,@281868 Hey! We've just sent a DM your way. Le...,678426,<NA>,[678426],[]
37976,2854424,SpotifyCares,False,2017-11-27 14:44:36+00:00,@793480 Hi there! We've just sent you a bit mo...,"2854425,2854426,2854427,2854428,2854429,285443...",<NA>,"[2854425, 2854426, 2854427, 2854428, 2854429, ...","[2854425, 2854426, 2854427, 2854428, 2854429, ..."
38354,2862778,SpotifyCares,False,2017-11-27 22:42:39+00:00,@785893 Hi! We've just sent you a bit more inf...,2862777,<NA>,[2862777],[]
38561,2871661,SpotifyCares,False,2017-11-28 02:57:11+00:00,@390066 We hear you. It looks like the email o...,2871660,<NA>,[2871660],[]
38791,2892624,SpotifyCares,False,2017-11-28 14:38:51+00:00,@801777 Hey! We've just sent a DM your way. Le...,2892623,<NA>,[2892623],[]
39050,89471,SpotifyCares,False,2017-11-28 21:17:28+00:00,"Something’s not quite right, and we’re looking...","89472,89470,89473,89474,89475,89476,89477,8947...",<NA>,"[89472, 89470, 89473, 89474, 89475, 89476, 894...","[89472, 89474, 89477, 89482, 89483, 89486, 894..."
39109,67684,SpotifyCares,False,2017-11-28 22:09:50+00:00,"All clear! Thanks for your patience, you rock....","67683,67685,67686,67687,67688,67689,67690,6769...",<NA>,"[67683, 67685, 67686, 67687, 67688, 67689, 676...","[67689, 67699, 67709, 67711, 67712, 67713, 677..."
41627,481114,SpotifyCares,False,2017-12-01 13:33:25+00:00,@229355 Hey! We've just sent you a bit more in...,481113,<NA>,[481113],[]

In [128]:
null_response = spotify_tweets[
    spotify_tweets["in_response_to_tweet_id"].isna()
]

# Inbound = True
inbound_true = null_response[
    null_response["inbound"] == True
]

# Inbound = False
inbound_false = null_response[
    null_response["inbound"] == False
]

print("Inbound = True:", len(inbound_true))
display(inbound_true)

print("Inbound = False:", len(inbound_false))
display(inbound_false)

Inbound = True: 0

Empty DataFrame
Columns: [tweet_id, author_id, inbound, created_at, text, response_tweet_id, in_response_to_tweet_id, response_ids, missing_response_ids]
Index: []

Inbound = False: 22

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
21,66018,SpotifyCares,False,2017-02-10 15:00:04+00:00,Let the pre-spring clean commence! https://t.c...,66017,<NA>,[66017],[]
481,293875,SpotifyCares,False,2017-10-04 14:20:13+00:00,Do not disturb 🚪 https://t.co/RZqTYGHtGB,"293876,293877,293878,293879,293874,293880,2938...",<NA>,"[293876, 293877, 293878, 293879, 293874, 29388...","[293883, 293885, 293888]"
4188,411607,SpotifyCares,False,2017-10-10 00:08:19+00:00,"Hey, help's here! Can you tell us what device ...","411608,411609,411610,411611,411612,411613,4116...",<NA>,"[411608, 411609, 411610, 411611, 411612, 41161...","[411608, 411609, 411610, 411612, 411613, 41161..."
5208,753638,SpotifyCares,False,2017-10-11 14:04:56+00:00,Attention playlist curators! We have two @1613...,"753637,753639,753640,753641,753642,753643,7536...",<NA>,"[753637, 753639, 753640, 753641, 753642, 75364...","[753641, 753643, 753646, 753649, 753651, 753652]"
8584,1261925,SpotifyCares,False,2017-10-16 04:32:42+00:00,Hi Will! Help's here. Can you let us know your...,"1261926,1261927,1261924,1261928,1261929,126193...",<NA>,"[1261926, 1261927, 1261924, 1261928, 1261929, ...","[1261927, 1261929, 1261931, 1261932]"
14226,1056940,SpotifyCares,False,2017-10-23 11:29:45+00:00,Discover Weekly: hand-picked just for you (but...,"1056939,1056941,1056942,1056943",<NA>,"[1056939, 1056941, 1056942, 1056943]",[]
19658,12091,SpotifyCares,False,2017-10-31 15:00:14+00:00,Resurrect your playlists 👻 https://t.co/8y3l3q...,"12090,12092,12093,12094,12095,12096,12097,1209...",<NA>,"[12090, 12092, 12093, 12094, 12095, 12096, 120...",[12102]
20484,58281,SpotifyCares,False,2017-11-01 20:15:35+00:00,@129236 Hey there! Can you send us the Album L...,58280,<NA>,[58280],[]
22085,1537070,SpotifyCares,False,2017-11-03 23:25:46+00:00,@476554 Got it. Find out how to reset your pas...,"1537071,1537069",<NA>,"[1537071, 1537069]",[1537071]
25116,2175496,SpotifyCares,False,2017-11-08 14:30:00+00:00,@637790 ¡Hola! La devolución del dinero depend...,"2175497,2175495",<NA>,"[2175497, 2175495]",[2175497]
25958,79405,SpotifyCares,False,2017-11-09 14:25:07+00:00,Twice the room to talk about that new tune! Sh...,"79404,79406,79407,79408,79409,79410,79411,7941...",<NA>,"[79404, 79406, 79407, 79408, 79409, 79410, 794...","[79406, 79414, 79416, 79421, 79423]"
27501,2276876,SpotifyCares,False,2017-11-11 14:33:13+00:00,"@662172 Hey, sorry for the wait! We've just re...",2276875,<NA>,[2276875],[]
31523,2582043,SpotifyCares,False,2017-11-16 22:42:34+00:00,@154077 Hey Patricia! We've just sent a DM you...,"2582042,2582044",<NA>,"[2582042, 2582044]",[2582044]
34340,2801580,SpotifyCares,False,2017-11-21 21:19:57+00:00,@663174 Hey there! We've just sent you a DM 🙂 /VK,"2801581,2801579",<NA>,"[2801581, 2801579]",[2801581]
35429,678427,SpotifyCares,False,2017-11-23 05:50:52+00:00,@281868 Hey! We've just sent a DM your way. Le...,678426,<NA>,[678426],[]
37976,2854424,SpotifyCares,False,2017-11-27 14:44:36+00:00,@793480 Hi there! We've just sent you a bit mo...,"2854425,2854426,2854427,2854428,2854429,285443...",<NA>,"[2854425, 2854426, 2854427, 2854428, 2854429, ...","[2854425, 2854426, 2854427, 2854428, 2854429, ..."
38354,2862778,SpotifyCares,False,2017-11-27 22:42:39+00:00,@785893 Hi! We've just sent you a bit more inf...,2862777,<NA>,[2862777],[]
38561,2871661,SpotifyCares,False,2017-11-28 02:57:11+00:00,@390066 We hear you. It looks like the email o...,2871660,<NA>,[2871660],[]
38791,2892624,SpotifyCares,False,2017-11-28 14:38:51+00:00,@801777 Hey! We've just sent a DM your way. Le...,2892623,<NA>,[2892623],[]
39050,89471,SpotifyCares,False,2017-11-28 21:17:28+00:00,"Something’s not quite right, and we’re looking...","89472,89470,89473,89474,89475,89476,89477,8947...",<NA>,"[89472, 89470, 89473, 89474, 89475, 89476, 894...","[89472, 89474, 89477, 89482, 89483, 89486, 894..."
39109,67684,SpotifyCares,False,2017-11-28 22:09:50+00:00,"All clear! Thanks for your patience, you rock....","67683,67685,67686,67687,67688,67689,67690,6769...",<NA>,"[67683, 67685, 67686, 67687, 67688, 67689, 676...","[67689, 67699, 67709, 67711, 67712, 67713, 677..."
41627,481114,SpotifyCares,False,2017-12-01 13:33:25+00:00,@229355 Hey! We've just sent you a bit more in...,481113,<NA>,[481113],[]

In [129]:
def find_parent_candidates(tweet_id, df):
    """
    Find tweets whose response_ids contain tweet_id.

    Parameters
    ----------
    tweet_id : int
        Tweet ID for which we want to find the parent.
    df : pd.DataFrame
        Full dataset containing tweet_id and response_ids.

    Returns
    -------
    pd.DataFrame
        Candidate parent tweets.
    """

    mask = df["response_ids"].apply(
        lambda ids: tweet_id in ids if isinstance(ids, list) else False
    )

    return df.loc[mask]

In [130]:
type(df['response_ids'][0])

list

In [131]:
def find_referencing_tweets(tweet_id, df):
    mask = df["response_ids"].apply(
        lambda ids: tweet_id in ids if isinstance(ids, list) else False
    )

    return df.loc[mask]

In [132]:
for tweet_id in null_response["tweet_id"]:
    
    candidates = find_referencing_tweets(tweet_id, df)

    print(f"\nSpotifyCares tweet: {tweet_id}")
    print(f"Referenced by {len(candidates)} tweet(s)")
    
    display(
        candidates[
            [
                "tweet_id",
                "author_id",
                "inbound",
                "text",
                "response_ids",
                "in_response_to_tweet_id"
            ]
        ]
    )

SpotifyCares tweet: 66018
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 293875
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 411607
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 753638
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 1261925
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 1056940
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 12091
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 58281
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 1537070
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2175496
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 79405
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2276876
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2582043
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2801580
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 678427
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2854424
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2862778
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2871661
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 2892624
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 89471
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 67684
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

SpotifyCares tweet: 481114
Referenced by 0 tweet(s)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids, in_response_to_tweet_id]
Index: []

In [133]:
def find_parent_from_response_ids(tweet_id, df):
    """
    Find tweets that explicitly list tweet_id in their response_ids.
    Returns candidate parent tweets.
    """

    mask = df["response_ids"].apply(
        lambda ids: tweet_id in ids if isinstance(ids, list) else False
    )

    candidates = df.loc[mask].copy()

    return candidates

In [134]:
tweet_id = 66018
parents = find_parent_from_response_ids(tweet_id, df)

display(
    parents[
        [
            "tweet_id",
            "author_id",
            "inbound",
            "text",
            "response_ids"
        ]
    ]
)

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, response_ids]
Index: []

In [135]:
spotify_tweets[
        spotify_tweets["response_tweet_id"].isna()
    ]

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
194,1982295,SpotifyCares,False,2017-10-02 06:45:33+00:00,@586767 Hey Janet! We're sad to hear you're le...,NaN,1982296,[],[]
235,727574,SpotifyCares,False,2017-10-03 15:41:46+00:00,@294294 Thanks for letting us know. Try restar...,NaN,727575,[],[]
246,1661594,SpotifyCares,False,2017-10-03 20:37:56+00:00,@306899 Hi there! Can you tell us what's happe...,NaN,1661595,[],[]
250,665362,SpotifyCares,False,2017-10-03 21:22:16+00:00,"@278546 2: having issues, the folks over @AskP...",NaN,665363,[],[]
258,237611,SpotifyCares,False,2017-10-03 23:32:53+00:00,@172577 2: when deleting songs using the mobil...,NaN,237612,[],[]
...,...,...,...,...,...,...,...,...,...
43260,603586,SpotifyCares,False,2017-12-03 22:50:40+00:00,@263421 Hey there! We don't have any info on t...,NaN,603587,[],[]
43261,603584,SpotifyCares,False,2017-12-03 22:51:30+00:00,@263420 Hey there! Could you confirm the count...,NaN,603585,[],[]
43262,603582,SpotifyCares,False,2017-12-03 22:54:06+00:00,@263419 Hey there! Could you tell us what devi...,NaN,603583,[],[]
43263,544574,SpotifyCares,False,2017-12-03 22:55:16+00:00,@232355 You're welcome. Let us know if you eve...,NaN,544572,[],[]
43264,567178,SpotifyCares,False,2017-12-03 22:56:04+00:00,@253022 Sometimes content gets temporarily rem...,NaN,567176,[],[]

In [136]:
# tweet_id -> list of tweets that directly respond to it

response_map = (
    df.dropna(subset=["in_response_to_tweet_id"])
      .groupby("in_response_to_tweet_id")["tweet_id"]
      .apply(list)
      .to_dict()
)

In [137]:
missing_mask = df["response_ids"].apply(
    lambda x: not isinstance(x, list) or len(x) == 0
)

df.loc[missing_mask, "response_ids"] = (
    df.loc[missing_mask, "tweet_id"]
      .map(response_map)
      .apply(lambda x: x if isinstance(x, list) else [])
)

In [138]:
print("Missing response_ids before:", missing_mask.sum())

Missing response_ids before: 1040629

In [139]:
remaining_missing = df["response_ids"].apply(
    lambda x: not isinstance(x, list) or len(x) == 0
)

print("Still empty:", remaining_missing.sum())
print("Reconstructed:", missing_mask.sum() - remaining_missing.sum())

Still empty: 1040629
Reconstructed: 0

In [140]:

# Build response mapping from the FULL dataset
# parent tweet_id -> child tweet_ids
response_map = (
    df.dropna(subset=["in_response_to_tweet_id"])
      .groupby("in_response_to_tweet_id")["tweet_id"]
      .apply(list)
      .to_dict()
)

# Find Spotify rows where response_ids is missing/empty
missing_mask = spotify_tweets["response_ids"].apply(
    lambda x: not isinstance(x, list) or len(x) == 0
)

print("Spotify missing response_ids:", missing_mask.sum())

# Fill ONLY Spotify missing response_ids
spotify_tweets.loc[missing_mask, "response_ids"] = (
    spotify_tweets.loc[missing_mask, "tweet_id"]
    .map(response_map)
    .apply(lambda x: x if isinstance(x, list) else [])
)

Spotify missing response_ids: 29479

In [141]:
# How many Spotify rows now have responses?
filled_mask = spotify_tweets["response_ids"].apply(
    lambda x: isinstance(x, list) and len(x) > 0
)

print("Spotify rows with response_ids:", filled_mask.sum())
print("Spotify rows still empty:", (~filled_mask).sum())

Spotify rows with response_ids: 13786
Spotify rows still empty: 29479

In [142]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,missing_response_ids
0,1,sprintcare,False,2017-10-31 22:10:47+00:00,@115712 I understand. I would like to assist y...,2,3,[2],[]
1,2,115712,True,2017-10-31 22:11:45+00:00,@sprintcare and how do you propose we do that,NaN,1,[],[]
2,3,115712,True,2017-10-31 22:08:27+00:00,@sprintcare I have sent several private messag...,1,4,[1],[]
3,4,sprintcare,False,2017-10-31 21:54:49+00:00,@115712 Please send us a Private Message so th...,3,5,[3],[]
4,5,115712,True,2017-10-31 21:49:35+00:00,@sprintcare I did.,4,6,[4],[]

In [143]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 9 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                str
 2   inbound                  bool
 3   created_at               datetime64[us, UTC]
 4   text                     str
 5   response_tweet_id        str
 6   in_response_to_tweet_id  Int64
 7   response_ids             object
 8   missing_response_ids     object
dtypes: Int64(1), bool(1), datetime64[us, UTC](1), int64(1), object(2), str(3)
memory usage: 177.0+ MB

In [144]:
spotify_tweets.isnull().sum()

tweet_id                       0
author_id                      0
inbound                        0
created_at                     0
text                           0
response_tweet_id          29479
in_response_to_tweet_id       22
response_ids                   0
missing_response_ids           0
dtype: int64

In [157]:
spotify_tweets = spotify_tweets.sort_values(
    by="created_at",
    ascending=True
).reset_index(drop=True)

In [158]:
spotify_tweets.to_csv(
    "spotify_brand.csv",
    index=False
)

In [145]:
spotify_tweets=spotify_tweets.drop(columns=["response_tweet_id"])

In [146]:
import pandas as pd

# ============================================================
# 1. Parent tweets
#    spotify_tweets.in_response_to_tweet_id -> df.tweet_id
# ============================================================

spotify_parent_matches = (
    spotify_tweets[
        spotify_tweets["in_response_to_tweet_id"].notna()
    ][
        [
            "tweet_id",
            "in_response_to_tweet_id",
            "text",
            "response_ids"          # maintain response_ids
        ]
    ]
    .merge(
        df[df["inbound"] == True][
            [
                "tweet_id",
                "author_id",
                "inbound",
                "created_at",
                "text"
            ]
        ],
        left_on="in_response_to_tweet_id",
        right_on="tweet_id",
        how="inner",
        suffixes=("_spotify", "_parent")
    )
)


# ============================================================
# 2. Response tweets
#    Maintain ORIGINAL response_ids
#    Use temporary column for matching
# ============================================================

spotify_response_matches = (
    spotify_tweets[
        [
            "tweet_id",
            "response_ids",
            "text"
        ]
    ]
    .assign(
        response_id_match=lambda x: x["response_ids"]
    )
    .explode("response_id_match")
    .merge(
        df[df["inbound"] == False][
            [
                "tweet_id",
                "author_id",
                "inbound",
                "created_at",
                "text",
                "in_response_to_tweet_id"
            ]
        ],
        left_on="response_id_match",
        right_on="tweet_id",
        how="inner",
        suffixes=("_spotify", "_response")
    )
)


# ============================================================
# Display results
# ============================================================

print(
    "Spotify → Customer parent matches:",
    len(spotify_parent_matches)
)

print(
    "Spotify → Customer response matches:",
    len(spotify_response_matches)
)


# ============================================================
# Parent matches
# ============================================================

display(
    spotify_parent_matches[
        [
            "tweet_id_spotify",
            "text_spotify",
            "in_response_to_tweet_id",
            "tweet_id_parent",
            "author_id",
            "inbound",
            "created_at",
            "text_parent",
            "response_ids"
        ]
    ]
)


# ============================================================
# Response matches
# ============================================================

display(
    spotify_response_matches[
        [
            "tweet_id_spotify",
            "text_spotify",

            # ORIGINAL COMPLETE response_ids list
            "response_ids",

            # Individual ID used for matching
            "response_id_match",

            "tweet_id_response",
            "author_id",
            "inbound",
            "created_at",
            "text_response",
            "in_response_to_tweet_id"
        ]
    ]
)

Spotify → Customer parent matches: 43092
Spotify → Customer response matches: 114

,tweet_id_spotify,text_spotify,in_response_to_tweet_id,tweet_id_parent,author_id,inbound,created_at,text_parent,response_ids
0,2926301,"@809660 Hey Scotty, what platform/device are y...",2926302,2926302,809660,True,2013-09-18 19:26:22+00:00,@SpotifyCares @112253 it says not available ...,[2926300]
1,979886,@352362 Hi! We're launching regularly in count...,979887,979887,352362,True,2015-08-12 16:50:56+00:00,Please make @115888 available for #India,[979885]
2,1824634,@188000 Hey Colin! Chromecast support is rolli...,1824636,1824636,188000,True,2015-10-02 19:56:39+00:00,@SpotifyCares Feature suggestion: ability to s...,[1824635]
3,281318,@183032 Hey there! Right now it's not possible...,281320,281320,183032,True,2015-10-06 21:37:04+00:00,hey @115888 can i get a profile photo without ...,[281319]
4,1405274,@446702 We don't have any more info to share a...,1405276,1405276,446702,True,2016-07-14 08:50:37+00:00,@SpotifyCares \nWhen will India get Spotify?😞,[1405275]
...,...,...,...,...,...,...,...,...,...
43087,603586,@263421 Hey there! We don't have any info on t...,603587,603587,263421,True,2017-12-03 10:44:19+00:00,"On this day last year, @115888 rolled out with...",[]
43088,603584,@263420 Hey there! Could you confirm the count...,603585,603585,263420,True,2017-12-03 10:49:02+00:00,"It's so sad, everytime i want to play a @28144...",[]
43089,603582,@263419 Hey there! Could you tell us what devi...,603583,603583,263419,True,2017-12-03 09:37:45+00:00,"@SpotifyCares hi there, I'm using google assis...",[]
43090,544574,@232355 You're welcome. Let us know if you eve...,544572,544572,232355,True,2017-12-03 13:26:31+00:00,@SpotifyCares Got it 😊Thanks admin. It's so he...,[]
43091,567178,@253022 Sometimes content gets temporarily rem...,567176,567176,253022,True,2017-12-03 13:40:02+00:00,@SpotifyCares ‘i mean’ and ‘complete’ by btob\...,[]

,tweet_id_spotify,text_spotify,response_ids,response_id_match,tweet_id_response,author_id,inbound,created_at,text_response,in_response_to_tweet_id
0,89509,"@5194 These might help, Pricilla! (although we...",[89508],89508,89508,SpotifyCares,False,2017-11-30 14:55:50+00:00,@5194 Hey Pricilla. These steps might help htt...,89509
1,1602805,@159663 Sweet. We can’t make any promises for ...,"[1602804, 1602806]",1602804,1602804,SpotifyCares,False,2017-11-05 07:10:11+00:00,@159663 No worries! Hopefully we'll be there s...,1602805
2,389437,@208173 Hey! Can you DM us your account's user...,"[389438, 389439]",389438,389438,SpotifyCares,False,2017-11-12 12:19:38+00:00,"@208173 Just to check, is this happening on 3G...",389437
3,1517964,"@472175 Thanks! Can you try logging out, resta...","[1517965, 1517966, 1517963]",1517965,1517965,SpotifyCares,False,2017-11-04 14:03:54+00:00,@472175 Hmm. Can you DM us your account's user...,1517964
4,1432642,@452660 Hi Richard! We've got info about this ...,[1432643],1432643,1432643,SpotifyCares,False,2017-11-03 20:02:15+00:00,"@452660 1: Hi again! To get the URI, just foll...",1432642
...,...,...,...,...,...,...,...,...,...,...
109,496140,"@233344 Hey Antonio, the cavalry's here! Just ...","[496141, 496142, 496143]",496141,496141,SpotifyCares,False,2017-12-01 19:18:32+00:00,"@233344 Hmm, that's odd. Can you let us know t...",496140
110,532739,@243411 Hey! The cavalry's here. Can you check...,"[532740, 532741]",532740,532740,SpotifyCares,False,2017-12-02 14:15:43+00:00,"@243411 Sweet! If you need anything else, just...",532739
111,555477,@249700 Hey Alec! Is this the podcast you're r...,"[555478, 555479]",555479,555479,SpotifyCares,False,2017-12-03 06:59:27+00:00,@249700 We can see how that’d be useful! Don't...,555477
112,578811,@256285 1: Hi Cassandra. We make music availab...,[578809],578809,578809,SpotifyCares,False,2017-12-03 10:53:16+00:00,@256285 2: Although Spotify doesn't censor mus...,578811
113,584156,@257826 Hmm. Can you fire over the versions of...,"[584157, 584158, 584159]",584157,584157,SpotifyCares,False,2017-12-03 14:41:55+00:00,@257826 No worries. Does this also happen when...,584156

In [147]:
spotify_parent_matches.isnull().sum()

tweet_id_spotify           0
in_response_to_tweet_id    0
text_spotify               0
response_ids               0
tweet_id_parent            0
author_id                  0
inbound                    0
created_at                 0
text_parent                0
dtype: int64

In [148]:
spotify_response_matches.shape

(114, 10)

In [149]:
spotify_tweets.head()

,tweet_id,author_id,inbound,created_at,text,in_response_to_tweet_id,response_ids,missing_response_ids
0,2926303,SpotifyCares,False,2013-09-18 19:23:17+00:00,@112253 We might need to take a look at your a...,2926304,[2926302],[]
1,2926301,SpotifyCares,False,2013-09-18 20:33:59+00:00,"@809660 Hey Scotty, what platform/device are y...",2926302,[2926300],[]
2,89509,SpotifyCares,False,2015-01-14 16:25:19+00:00,"@5194 These might help, Pricilla! (although we...",89510,[89508],[]
3,979886,SpotifyCares,False,2015-08-12 18:44:00+00:00,@352362 Hi! We're launching regularly in count...,979887,[979885],[]
4,1824634,SpotifyCares,False,2015-10-03 01:06:51+00:00,@188000 Hey Colin! Chromecast support is rolli...,1824636,[1824635],[]

In [168]:
len(spotify_tweets[spotify_tweets["response_ids"].apply(len) == 0])

29479

In [151]:
spotify_parent_matches.isnull().sum()

tweet_id_spotify           0
in_response_to_tweet_id    0
text_spotify               0
response_ids               0
tweet_id_parent            0
author_id                  0
inbound                    0
created_at                 0
text_parent                0
dtype: int64

In [152]:
spotify_mentions = spotify_tweets[
    spotify_tweets["text"].str.contains(
        r"(?<![A-Za-z0-9_])@SpotifyCares(?![A-Za-z0-9_])",
        case=False,
        na=False
    )
].copy()

In [153]:
# Spotify tweet IDs found in parent matches
parent_tweet_ids = set(
    spotify_parent_matches["tweet_id_spotify"]
    .dropna()
)

# Spotify tweet IDs found in response matches
response_tweet_ids = set(
    spotify_response_matches["tweet_id_spotify"]
    .dropna()
)

# Add match status
spotify_mentions["in_parent_matches"] = (
    spotify_mentions["tweet_id"].isin(parent_tweet_ids)
)

spotify_mentions["in_response_matches"] = (
    spotify_mentions["tweet_id"].isin(response_tweet_ids)
)

# ============================================================
# Summary
# ============================================================

print(
    "Total @SpotifyCares tweets:",
    len(spotify_mentions)
)

print(
    "Present in parent matches:",
    spotify_mentions["in_parent_matches"].sum()
)

print(
    "Present in response matches:",
    spotify_mentions["in_response_matches"].sum()
)

print(
    "Present in either parent or response:",
    (
        spotify_mentions["in_parent_matches"]
        | spotify_mentions["in_response_matches"]
    ).sum()
)

print(
    "Present in neither:",
    (
        ~spotify_mentions["in_parent_matches"]
        & ~spotify_mentions["in_response_matches"]
    ).sum()
)

# ============================================================
# Display
# ============================================================

display(
    spotify_mentions[
        [
            "tweet_id",
            "author_id",
            "created_at",
            "text",
            "in_parent_matches",
            "in_response_matches"
        ]
    ]
)

Total @SpotifyCares tweets: 1
Present in parent matches: 1
Present in response matches: 0
Present in either parent or response: 1
Present in neither: 0

,tweet_id,author_id,created_at,text,in_parent_matches,in_response_matches
41853,499272,SpotifyCares,2017-12-01 19:09:05+00:00,@234235 Hey Hailey! We'd be glad to help out. ...,True,False

In [154]:
spotify_mentions_unmatched = spotify_mentions[
    ~spotify_mentions["in_parent_matches"]
    & ~spotify_mentions["in_response_matches"]
].copy()

print(
    "Unmatched @SpotifyCares tweets:",
    len(spotify_mentions_unmatched)
)

display(spotify_mentions_unmatched)

Unmatched @SpotifyCares tweets: 0

Empty DataFrame
Columns: [tweet_id, author_id, inbound, created_at, text, in_response_to_tweet_id, response_ids, missing_response_ids, in_parent_matches, in_response_matches]
Index: []

In [159]:
parent_ids = spotify_tweets['in_response_to_tweet_id'].dropna().astype('int64')

# Step 2: Look these up in the FULL dataset, restricted to inbound=True
customer_questions = df[
    (df['tweet_id'].isin(parent_ids)) &
    (df['inbound'] == True)
].copy()

print("Customer questions found:", len(customer_questions))
display(customer_questions[['tweet_id', 'author_id', 'inbound', 'created_at', 'text']])

Customer questions found: 41585

,tweet_id,author_id,inbound,created_at,text
541,849,115887,True,2017-10-31 23:36:20+00:00,@SpotifyCares doesn’t work and i even tried de...
543,850,115887,True,2017-10-31 21:41:37+00:00,@SpotifyCares Premium &amp; when i️ have it on...
545,853,115887,True,2017-10-31 19:57:59+00:00,@SpotifyCares iphone 7+ and i have the most re...
547,855,115887,True,2017-10-31 19:10:51+00:00,i’m pissed my @115888 shuffle and repeat butto...
549,857,115889,True,2017-11-01 07:40:06+00:00,"@SpotifyCares Yes, multiple times. No changes...."
...,...,...,...,...,...
2811210,2987394,149099,True,2017-11-30 07:22:22+00:00,"@SpotifyCares Hey guys, new problem this time...."
2811213,2987397,823708,True,2017-11-30 07:24:28+00:00,@115888 @SpotifyCares got invited to a special...
2811215,2987399,823514,True,2017-11-30 07:32:25+00:00,@SpotifyCares what do I do??? https://t.co/Ca...
2811217,2987401,823709,True,2017-11-30 07:20:48+00:00,"@SpotifyCares Hey Guys, my family members cann..."
2811504,2987685,823786,True,2017-10-31 22:01:40+00:00,@SpotifyCares I tried on many devices and brow...

In [163]:
customer_questions = customer_questions.sort_values(
    by="created_at",
    ascending=True
).reset_index(drop=True)

In [162]:
customer_questions.to_csv(
    "spotify_customer.csv",
    index=False
)

In [165]:
spotify_tweets.isnull().sum()

tweet_id                    0
author_id                   0
inbound                     0
created_at                  0
text                        0
in_response_to_tweet_id    22
response_ids                0
missing_response_ids        0
dtype: int64

In [164]:
qa_pairs = customer_questions.merge(
    spotify_tweets,
    left_on='tweet_id',
    right_on='in_response_to_tweet_id',
    suffixes=('_question', '_answer'),
    how='inner'
)

print("Total Q&A pairs formed:", len(qa_pairs))
display(qa_pairs[[
    'tweet_id_question', 'author_id_question', 'text_question',
    'tweet_id_answer', 'author_id_answer', 'text_answer'
]].head())

Total Q&A pairs formed: 43092

,tweet_id_question,author_id_question,text_question,tweet_id_answer,author_id_answer,text_answer
0,2926302,809660,@SpotifyCares @112253 it says not available ...,2926301,SpotifyCares,"@809660 Hey Scotty, what platform/device are y..."
1,1374248,439867,Mola cómo ha quedado Spotify. #FreshSpotify ht...,1374247,SpotifyCares,@439867 ¡Hola! La ayuda llegó. ¿Podrías seguir...
2,979887,352362,Please make @115888 available for #India,979886,SpotifyCares,@352362 Hi! We're launching regularly in count...
3,1824636,188000,@SpotifyCares Feature suggestion: ability to s...,1824634,SpotifyCares,@188000 Hey Colin! Chromecast support is rolli...
4,281320,183032,hey @115888 can i get a profile photo without ...,281318,SpotifyCares,@183032 Hey there! Right now it's not possible...

In [170]:
qa_pairs.to_csv(
    "spotify_brand_customer_conversations.csv",
    index=False
)

In [171]:
qa_pairs.dtypes

tweet_id_question                                 int64
author_id_question                                  str
inbound_question                                   bool
created_at_question                 datetime64[us, UTC]
text_question                                       str
response_tweet_id                                   str
in_response_to_tweet_id_question                  Int64
response_ids_question                            object
missing_response_ids_question                    object
tweet_id_answer                                   int64
author_id_answer                                    str
inbound_answer                                     bool
created_at_answer                   datetime64[us, UTC]
text_answer                                         str
in_response_to_tweet_id_answer                    Int64
response_ids_answer                              object
missing_response_ids_answer                      object
dtype: object

In [ ]:
spotify_tweets[spotify_tweets["author_id"]==188000]

Empty DataFrame
Columns: [tweet_id, author_id, inbound, created_at, text, missing_response_ids, mentioned_handles, in_response_to_tweet_id, response_ids, extracted_author_id]
Index: []

In [3]:
from pathlib import Path
import pandas as pd
file_path_cluster=Path().resolve().parent / "intent"/"output"/"cluster_summary.csv"
cluster_summary=pd.read_csv(file_path_cluster)

In [6]:
cluster_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cluster_id    188 non-null    int64
 1   intent_label  188 non-null    str
 2   display_name  188 non-null    str
 3   description   188 non-null    str
 4   num_tweets    188 non-null    int64
 5   top_keywords  187 non-null    str
dtypes: int64(2), str(4)
memory usage: 8.9 KB

In [4]:
cluster_summary_ = cluster_summary.sort_values(
    by="cluster_id",
    ascending=True
).reset_index(drop=True)

In [5]:
cluster_summary.to_csv(
    "spotify_tweet_cluster.csv",
    index=False
)

Update complete!

In [20]:
from pathlib import Path
import pandas as pd
file_path_cluster=Path().resolve().parent / "experiments"/"tweets_with_intents.csv"
tweets_with_intent=pd.read_csv(file_path_cluster)

In [21]:

# 2. Locate the rows where intent_label is 146 and update both columns
# Note: If your intent_label column is formatted as text/string, use '146' instead of 146
tweets_with_intent.loc[tweets_with_intent['cluster'] == 146, ['intent_label', 'intent_display_name']] = 'student_discount_issue'

tweets_with_intent.to_csv('tweets_with_intent.csv', index=False)

print("Update complete!")

Update complete!